export interface SeedDependency {
  source: string; // slug
  target: string; // slug
  type: "runtime" | "build" | "api" | "shared-library";
}

export const DEPENDENCIES: SeedDependency[] = [
  { source: "payment-gateway-service", target: "fraud-detection-engine", type: "api" },
  { source: "payment-gateway-service", target: "identity-auth-service", type: "api" },
  { source: "payment-gateway-service", target: "secrets-management-service", type: "runtime" },
  { source: "billing-invoicing-api", target: "payment-gateway-service", type: "api" },
  { source: "billing-invoicing-api", target: "subscription-management-service", type: "api" },
  { source: "settlement-reconciliation-worker", target: "payment-gateway-service", type: "api" },
  { source: "refund-processing-service", target: "payment-gateway-service", type: "api" },
  { source: "gift-card-service", target: "payment-gateway-service", type: "api" },
  { source: "vendor-payout-service", target: "payment-gateway-service", type: "api" },
  { source: "regional-tax-calculation-service", target: "billing-invoicing-api", type: "api" },
  { source: "subscription-management-service", target: "billing-invoicing-api", type: "api" },
  { source: "subscription-management-service", target: "notification-service", type: "api" },

  { source: "sso-gateway", target: "identity-auth-service", type: "api" },
  { source: "permissions-rbac-service", target: "identity-auth-service", type: "api" },
  { source: "api-key-management", target: "identity-auth-service", type: "api" },
  { source: "customer-web-portal", target: "identity-auth-service", type: "api" },
  { source: "customer-mobile-app-backend", target: "identity-auth-service", type: "api" },
  { source: "internal-search-service", target: "sso-gateway", type: "api" },
  { source: "config-management-service", target: "secrets-management-service", type: "runtime" },

  { source: "customer-web-portal", target: "api-gateway", type: "api" },
  { source: "customer-mobile-app-backend", target: "api-gateway", type: "api" },
  { source: "customer-web-portal", target: "shared-ui-component-library", type: "shared-library" },
  { source: "customer-support-widget", target: "shared-ui-component-library", type: "shared-library" },
  { source: "reporting-dashboard-service", target: "shared-ui-component-library", type: "shared-library" },
  { source: "internal-status-page", target: "shared-ui-component-library", type: "shared-library" },
  { source: "customer-web-portal", target: "notification-service", type: "api" },
  { source: "customer-mobile-app-backend", target: "mobile-push-notification-gateway", type: "api" },
  { source: "notification-service", target: "customer-notification-preferences", type: "api" },
  { source: "mobile-push-notification-gateway", target: "customer-notification-preferences", type: "api" },
  { source: "customer-web-portal", target: "loyalty-rewards-service", type: "api" },
  { source: "customer-web-portal", target: "wishlist-favorites-service", type: "api" },
  { source: "customer-web-portal", target: "review-ratings-service", type: "api" },
  { source: "customer-web-portal", target: "search-catalog-indexer", type: "api" },
  { source: "customer-mobile-app-backend", target: "search-catalog-indexer", type: "api" },
  { source: "legacy-customer-portal", target: "legacy-payment-processor", type: "api" },
  { source: "email-alert-dispatcher-v1", target: "legacy-customer-portal", type: "api" },

  { source: "order-fulfillment-service", target: "warehouse-inventory-api", type: "api" },
  { source: "order-fulfillment-service", target: "shipping-carrier-integration", type: "api" },
  { source: "order-fulfillment-service", target: "payment-gateway-service", type: "api" },
  { source: "order-fulfillment-service", target: "notification-service", type: "api" },
  { source: "returns-processing-service", target: "warehouse-inventory-api", type: "api" },
  { source: "returns-processing-service", target: "refund-processing-service", type: "api" },
  { source: "returns-fraud-heuristics", target: "returns-processing-service", type: "api" },
  { source: "delivery-route-optimizer", target: "shipping-carrier-integration", type: "api" },
  { source: "warehouse-robotics-controller", target: "warehouse-inventory-api", type: "api" },
  { source: "supplier-edi-integration", target: "warehouse-inventory-api", type: "api" },
  { source: "legacy-warehouse-management-system", target: "mainframe-integration-adapter", type: "runtime" },

  { source: "analytics-ingestion-pipeline", target: "api-gateway", type: "api" },
  { source: "customer-data-warehouse-etl", target: "analytics-ingestion-pipeline", type: "runtime" },
  { source: "reporting-dashboard-service", target: "customer-data-warehouse-etl", type: "runtime" },
  { source: "ml-recommendation-engine", target: "customer-data-warehouse-etl", type: "runtime" },
  { source: "customer-churn-prediction", target: "customer-data-warehouse-etl", type: "runtime" },
  { source: "ab-testing-platform", target: "analytics-ingestion-pipeline", type: "runtime" },
  { source: "personalization-engine", target: "ml-recommendation-engine", type: "api" },
  { source: "data-quality-monitor", target: "analytics-ingestion-pipeline", type: "runtime" },
  { source: "legacy-batch-reporting-job", target: "legacy-warehouse-management-system", type: "runtime" },

  { source: "campaign-management-service", target: "crm-integration-service", type: "api" },
  { source: "campaign-management-service", target: "notification-service", type: "api" },
  { source: "campaign-management-service", target: "email-marketing-templates", type: "shared-library" },
  { source: "personalization-engine", target: "campaign-management-service", type: "api" },
  { source: "affiliate-tracking-service", target: "crm-integration-service", type: "api" },
  { source: "social-media-listening-tool", target: "crm-integration-service", type: "api" },
  { source: "legacy-marketing-automation-tool", target: "crm-integration-service", type: "api" },

  { source: "customer-web-portal", target: "feature-flag-service", type: "api" },
  { source: "customer-mobile-app-backend", target: "feature-flag-service", type: "api" },
  { source: "api-gateway", target: "identity-auth-service", type: "api" },
  { source: "api-gateway", target: "observability-metrics-service", type: "runtime" },
  { source: "webhook-relay-service", target: "api-gateway", type: "api" },
  { source: "internal-developer-cli", target: "ci-cd-pipeline-templates", type: "build" },
  { source: "ci-cd-pipeline-templates", target: "infra-terraform-modules", type: "build" },
  { source: "monorepo-build-tooling", target: "shared-ui-component-library", type: "build" },
  { source: "experimental-graphql-gateway", target: "api-gateway", type: "api" },
  { source: "batch-job-scheduler", target: "observability-metrics-service", type: "runtime" },
];
