export interface SeedIntentDef {
  purpose: string;
  inputs: string[];
  outputs: string[];
  successCriteria: string[];
  constraints: string[];
  risks: string[];
}

// Keyed by repository slug. Only repos with hasIntent: true in repositories.ts
// need an entry here; the seed runner falls back to a minimal generated
// intent (marked low-confidence) for any hasIntent repo without a
// hand-authored entry below, and skips intent generation entirely for repos
// marked hasIntent: false (demonstrating "missing intent" findings).
export const INTENTS: Record<string, SeedIntentDef> = {
  "payment-gateway-service": {
    purpose: "Process customer payment transactions across multiple payment methods, including cards, ACH, and digital wallets.",
    inputs: ["Authorization requests", "Card and wallet tokens", "Merchant account configuration"],
    outputs: ["Authorization responses", "Transaction records", "Settlement events"],
    successCriteria: [
      "Transactions are authorized within SLA latency targets",
      "Declined transactions return actionable decline codes",
      "All transactions are recorded for downstream reconciliation",
    ],
    constraints: ["Must remain PCI-DSS scope compliant", "No card data persisted outside tokenization vault"],
    risks: ["High-traffic dependency for nearly all commerce flows — outage blast radius is large"],
  },
  "billing-invoicing-api": {
    purpose: "Generate invoices and manage recurring billing cycles for customer accounts.",
    inputs: ["Subscription billing events", "Usage records", "Tax calculation results"],
    outputs: ["Customer invoices", "Billing statements", "Dunning notifications"],
    successCriteria: ["Invoices generated accurately on billing cycle boundaries", "Failed charges trigger dunning workflow"],
    constraints: ["Must support multiple currencies and tax jurisdictions"],
    risks: ["Invoice generation logic duplicated in legacy-payment-processor for a subset of accounts"],
  },
  "settlement-reconciliation-worker": {
    purpose: "Reconcile daily settlement files from payment processors against internal transaction ledgers.",
    inputs: ["Processor settlement files", "Internal transaction ledger"],
    outputs: ["Reconciliation reports", "Discrepancy alerts"],
    successCriteria: ["Daily reconciliation completes before end-of-day close", "Discrepancies over threshold are flagged"],
    constraints: ["Must process files from multiple processor formats"],
    risks: [],
  },
  "legacy-payment-processor": {
    purpose: "Legacy payment processing for a small number of remaining merchant integrations not yet migrated to payment-gateway-service.",
    inputs: ["Legacy merchant authorization requests"],
    outputs: ["Legacy authorization responses"],
    successCriteria: ["Remaining merchant integrations continue to authorize successfully"],
    constraints: ["Running on unsupported Apache Struts version"],
    risks: ["Overlapping capability with payment-gateway-service", "Security patching lagging due to outdated framework"],
  },
  "fraud-detection-engine": {
    purpose: "Score transactions in real time for fraud risk before authorization.",
    inputs: ["Transaction events", "Customer behavioral signals", "Device fingerprint data"],
    outputs: ["Fraud risk scores", "Block/allow decisions"],
    successCriteria: ["Scoring completes within sub-100ms latency budget", "False positive rate stays under target threshold"],
    constraints: ["Must not introduce checkout latency beyond SLA"],
    risks: [],
  },
  "identity-auth-service": {
    purpose: "Authenticate users and issue signed session tokens for internal and external applications.",
    inputs: ["Login credentials", "OAuth authorization requests", "MFA challenges"],
    outputs: ["Signed session tokens", "Refresh tokens", "Authentication audit events"],
    successCriteria: ["Token issuance succeeds under peak login load", "Compromised sessions can be revoked immediately"],
    constraints: ["Must support enterprise SSO federation", "Token signing keys rotated on schedule"],
    risks: [],
  },
  "sso-gateway": {
    purpose: "Provide single sign-on federation across internal enterprise applications.",
    inputs: ["SAML/OIDC assertions", "Identity provider metadata"],
    outputs: ["Federated session tokens"],
    successCriteria: ["Users authenticate once across federated applications"],
    constraints: ["Must support both SAML and OIDC protocols"],
    risks: [],
  },
  "permissions-rbac-service": {
    purpose: "Manage roles, permissions, and access policies for internal applications.",
    inputs: ["Role definitions", "Permission assignment requests"],
    outputs: ["Access decisions", "Role/permission audit trail"],
    successCriteria: ["Access checks resolve correctly for all defined roles"],
    constraints: [],
    risks: [],
  },
  "customer-web-portal": {
    purpose: "Provide customers a self-service web portal for account and order management.",
    inputs: ["Customer account data", "Order history", "Support requests"],
    outputs: ["Rendered account management UI", "Order status updates"],
    successCriteria: ["Portal renders correctly across supported browsers", "Core account tasks completable without support contact"],
    constraints: ["Must meet WCAG 2.1 AA accessibility standards"],
    risks: [],
  },
  "customer-mobile-app-backend": {
    purpose: "Serve mobile-optimized APIs for the iOS and Android customer applications.",
    inputs: ["Mobile app API requests", "Push notification triggers"],
    outputs: ["Mobile-optimized API responses"],
    successCriteria: ["API responses stay within mobile latency budget", "Backward compatibility maintained across app versions"],
    constraints: ["Must support at least two prior mobile app major versions"],
    risks: [],
  },
  "notification-service": {
    purpose: "Provide customer notification services across email and SMS.",
    inputs: ["Notification requests", "Customer communication preferences", "Message templates"],
    outputs: ["Email messages", "SMS messages", "Delivery events"],
    successCriteria: [
      "Requests are accepted through the notification API",
      "Customer communication preferences are honored",
      "Delivery status is recorded",
      "Failed deliveries follow retry policies",
    ],
    constraints: ["customer-preferences-api", "sms-gateway", "email-provider-adapter"],
    risks: ["Overlapping notification capability found in email-alert-dispatcher-v1", "README documentation is stale"],
  },
  "customer-notification-preferences": {
    purpose: "Store and enforce customer notification channel preferences.",
    inputs: ["Preference update requests"],
    outputs: ["Preference lookups", "Opt-out enforcement decisions"],
    successCriteria: ["Opt-outs are honored on the next notification attempt"],
    constraints: [],
    risks: [],
  },
  "loyalty-rewards-service": {
    purpose: "Track customer loyalty points and process rewards redemption.",
    inputs: ["Purchase events", "Redemption requests"],
    outputs: ["Points balance updates", "Redemption confirmations"],
    successCriteria: ["Points accrue correctly on qualifying purchases"],
    constraints: [],
    risks: [],
  },
  "legacy-customer-portal": {
    purpose: "Serve a legacy web experience to a shrinking set of enterprise clients not yet migrated to customer-web-portal.",
    inputs: ["Legacy client account data"],
    outputs: ["Legacy portal UI"],
    successCriteria: ["Remaining enterprise clients retain access until migration"],
    constraints: ["Built on unsupported AngularJS and jQuery"],
    risks: ["Substantially duplicates customer-web-portal capability", "Very low remaining activity — strong archive candidate"],
  },
  "order-fulfillment-service": {
    purpose: "Orchestrate the fulfillment lifecycle of customer orders from confirmation to shipment.",
    inputs: ["Confirmed order events", "Inventory availability", "Shipping rate quotes"],
    outputs: ["Fulfillment status events", "Shipment records"],
    successCriteria: ["Orders progress through fulfillment states without manual intervention in the common case"],
    constraints: ["Must coordinate across multiple warehouse regions"],
    risks: [],
  },
  "warehouse-inventory-api": {
    purpose: "Track real-time inventory levels and reservations across distribution centers.",
    inputs: ["Inventory count updates", "Reservation requests"],
    outputs: ["Current inventory levels", "Reservation confirmations"],
    successCriteria: ["Inventory counts stay consistent with physical warehouse counts within tolerance"],
    constraints: [],
    risks: [],
  },
  "shipping-carrier-integration": {
    purpose: "Integrate with shipping carriers to fetch rates and generate shipping labels.",
    inputs: ["Shipment details", "Carrier rate requests"],
    outputs: ["Rate quotes", "Shipping labels", "Tracking numbers"],
    successCriteria: ["Rate quotes returned within checkout latency budget"],
    constraints: ["Must support multiple carrier APIs"],
    risks: [],
  },
  "legacy-warehouse-management-system": {
    purpose: "Manage warehouse operations for facilities not yet migrated to the modern fulfillment platform.",
    inputs: ["Warehouse floor transactions"],
    outputs: ["Inventory movement records"],
    successCriteria: ["Remaining facilities continue operating without disruption"],
    constraints: ["Running on COBOL with limited remaining institutional knowledge"],
    risks: ["Key-person risk — very few engineers can maintain this system", "No automated test coverage"],
  },
  "delivery-route-optimizer": {
    purpose: "Compute optimized last-mile delivery routes for regional delivery fleets.",
    inputs: ["Delivery addresses", "Vehicle capacity constraints"],
    outputs: ["Optimized route plans"],
    successCriteria: ["Computed routes reduce average delivery distance versus baseline"],
    constraints: [],
    risks: [],
  },
  "analytics-ingestion-pipeline": {
    purpose: "Ingest and normalize event data from application services into the enterprise data warehouse.",
    inputs: ["Application event streams", "Service log data"],
    outputs: ["Normalized warehouse-ready event records"],
    successCriteria: ["Events land in the warehouse within defined freshness SLA"],
    constraints: ["Must handle schema evolution without pipeline failures"],
    risks: [],
  },
  "reporting-dashboard-service": {
    purpose: "Serve business reporting dashboards to executive and operational stakeholders.",
    inputs: ["Warehouse query results"],
    outputs: ["Rendered dashboards", "Scheduled report exports"],
    successCriteria: ["Dashboards load within acceptable latency for stakeholder use"],
    constraints: [],
    risks: [],
  },
  "customer-data-warehouse-etl": {
    purpose: "Transform raw customer event and transaction data into warehouse-ready analytical schemas.",
    inputs: ["Raw event data", "Raw transaction data"],
    outputs: ["Analytical fact and dimension tables"],
    successCriteria: ["Transformations complete nightly without data loss"],
    constraints: [],
    risks: [],
  },
  "ml-recommendation-engine": {
    purpose: "Generate personalized product recommendations using customer behavioral and purchase data.",
    inputs: ["Customer behavioral data", "Purchase history"],
    outputs: ["Ranked product recommendations"],
    successCriteria: ["Recommendations improve click-through rate versus non-personalized baseline"],
    constraints: [],
    risks: [],
  },
  "campaign-management-service": {
    purpose: "Define, schedule, and track marketing campaigns across channels.",
    inputs: ["Campaign definitions", "Audience segments"],
    outputs: ["Scheduled campaign executions", "Campaign performance metrics"],
    successCriteria: ["Campaigns execute on schedule to the correct audience segment"],
    constraints: [],
    risks: [],
  },
  "crm-integration-service": {
    purpose: "Synchronize customer and lead records between internal systems and the CRM platform.",
    inputs: ["Customer record updates", "CRM webhook events"],
    outputs: ["Synchronized CRM records"],
    successCriteria: ["Record changes propagate to the CRM within defined sync window"],
    constraints: [],
    risks: [],
  },
  "personalization-engine": {
    purpose: "Personalize on-site and email content in real time based on customer segments.",
    inputs: ["Customer segment data", "Content variants"],
    outputs: ["Personalized content selections"],
    successCriteria: ["Personalized variants selected within page render latency budget"],
    constraints: [],
    risks: [],
  },
  "ci-cd-pipeline-templates": {
    purpose: "Provide reusable CI/CD pipeline templates and standards for engineering teams.",
    inputs: ["Repository build configuration"],
    outputs: ["Standardized pipeline definitions"],
    successCriteria: ["Teams can adopt a standard pipeline without custom scripting"],
    constraints: [],
    risks: [],
  },
  "infra-terraform-modules": {
    purpose: "Provide reusable, versioned Terraform modules for provisioning cloud infrastructure.",
    inputs: ["Module configuration variables"],
    outputs: ["Provisioned cloud infrastructure"],
    successCriteria: ["Modules provision infrastructure consistently across environments"],
    constraints: ["Must remain compatible with the organization's cloud provider baseline"],
    risks: [],
  },
  "shared-ui-component-library": {
    purpose: "Provide a shared, versioned React component library implementing the enterprise design system.",
    inputs: ["Design system tokens", "Component specifications"],
    outputs: ["Published component library packages"],
    successCriteria: ["Consuming applications render consistent UI using shared components"],
    constraints: [],
    risks: [],
  },
  "api-gateway": {
    purpose: "Route, authenticate, and rate-limit traffic to internal microservices.",
    inputs: ["Inbound API requests", "Routing configuration"],
    outputs: ["Routed requests", "Rate-limit decisions"],
    successCriteria: ["Requests routed correctly with authentication enforced"],
    constraints: ["Must not become a single point of failure for all traffic"],
    risks: [],
  },
  "observability-metrics-service": {
    purpose: "Aggregate application and infrastructure metrics for observability dashboards and alerting.",
    inputs: ["Service metric emissions"],
    outputs: ["Aggregated metrics", "Alert triggers"],
    successCriteria: ["Metrics available for on-call use within near-real-time latency"],
    constraints: [],
    risks: [],
  },
  "feature-flag-service": {
    purpose: "Manage feature flags and gradual rollout configuration for internal applications.",
    inputs: ["Flag configuration changes"],
    outputs: ["Flag evaluation results"],
    successCriteria: ["Flag changes propagate to consuming applications within seconds"],
    constraints: [],
    risks: [],
  },
  "secrets-management-service": {
    purpose: "Manage and rotate application secrets, integrating with the enterprise vault.",
    inputs: ["Secret creation and rotation requests"],
    outputs: ["Secret retrieval responses", "Rotation audit events"],
    successCriteria: ["Secrets rotate on schedule without service disruption"],
    constraints: ["Must never log secret values"],
    risks: [],
  },
  "webhook-relay-service": {
    purpose: "Relay and reliably retry webhook delivery between internal services and partner systems.",
    inputs: ["Outbound webhook events", "Inbound partner webhooks"],
    outputs: ["Delivered webhook payloads", "Delivery status records"],
    successCriteria: ["Failed deliveries retry according to backoff policy"],
    constraints: [],
    risks: [],
  },
  "regional-tax-calculation-service": {
    purpose: "Calculate applicable sales tax for order totals based on shipping jurisdiction.",
    inputs: ["Order line items", "Shipping jurisdiction"],
    outputs: ["Calculated tax amounts"],
    successCriteria: ["Tax calculated correctly for all supported jurisdictions"],
    constraints: ["Must stay current with jurisdiction tax rate changes"],
    risks: [],
  },
  "subscription-management-service": {
    purpose: "Manage recurring subscription plans, upgrades, downgrades, and cancellations.",
    inputs: ["Subscription lifecycle requests"],
    outputs: ["Subscription state changes", "Billing trigger events"],
    successCriteria: ["Plan changes take effect on the correct billing boundary"],
    constraints: [],
    risks: [],
  },
  "vendor-payout-service": {
    purpose: "Calculate and issue periodic payouts to third-party marketplace vendors.",
    inputs: ["Vendor sales records", "Commission rate configuration"],
    outputs: ["Payout calculations", "Payout disbursement events"],
    successCriteria: ["Payouts calculated accurately on the scheduled cadence"],
    constraints: [],
    risks: [],
  },
  "mobile-push-notification-gateway": {
    purpose: "Deliver push notifications to iOS and Android customer applications.",
    inputs: ["Push notification requests", "Device tokens"],
    outputs: ["Delivered push notifications"],
    successCriteria: ["Notifications delivered within acceptable latency across both platforms"],
    constraints: [],
    risks: [],
  },
  "review-ratings-service": {
    purpose: "Store, moderate, and serve customer product reviews and ratings.",
    inputs: ["Submitted reviews", "Moderation decisions"],
    outputs: ["Published reviews", "Aggregate rating scores"],
    successCriteria: ["Reviews moderated before becoming publicly visible"],
    constraints: [],
    risks: [],
  },
  "search-catalog-indexer": {
    purpose: "Index product catalog data to power on-site product search.",
    inputs: ["Product catalog updates"],
    outputs: ["Search index updates"],
    successCriteria: ["Catalog changes reflected in search results within freshness SLA"],
    constraints: [],
    risks: [],
  },
  "supplier-edi-integration": {
    purpose: "Process EDI purchase orders and invoices exchanged with wholesale suppliers.",
    inputs: ["Inbound EDI documents"],
    outputs: ["Parsed purchase orders", "Parsed supplier invoices"],
    successCriteria: ["EDI documents parsed without manual correction in the common case"],
    constraints: ["Must support legacy EDI X12 formats used by long-standing suppliers"],
    risks: [],
  },
  "customer-churn-prediction": {
    purpose: "Predict customer churn risk to inform retention campaigns.",
    inputs: ["Customer engagement history", "Subscription status"],
    outputs: ["Churn risk scores"],
    successCriteria: ["Churn scores correlate with actual churn outcomes above baseline"],
    constraints: [],
    risks: [],
  },
  "ab-testing-platform": {
    purpose: "Configure experiments and compute statistical significance for A/B tests across products.",
    inputs: ["Experiment configuration", "Event data for treatment/control groups"],
    outputs: ["Statistical significance results"],
    successCriteria: ["Results computed correctly with appropriate significance thresholds"],
    constraints: [],
    risks: [],
  },
  "mainframe-integration-adapter": {
    purpose: "Translate legacy mainframe batch file outputs into modern event streams.",
    inputs: ["Mainframe batch output files"],
    outputs: ["Modern event stream records"],
    successCriteria: ["Batch outputs translated without data loss"],
    constraints: ["Dependent on legacy mainframe batch schedule"],
    risks: ["Sole remaining bridge between mainframe and modern systems — high criticality, low documentation"],
  },
};
