import type { DomainId, TeamId, TechId } from "./reference-data.js";

export type Lifecycle =
  | "Active"
  | "Maintenance"
  | "Legacy"
  | "Dormant"
  | "Archive Candidate"
  | "Archived"
  | "Unknown";

export interface SeedRepoDef {
  slug: string;
  name: string;
  description: string;
  inferredPurpose: string;
  provider: "github" | "gitlab" | "azure-devops" | "bitbucket";
  visibility: "public" | "internal" | "private";
  team: TeamId | null;
  domain: DomainId | null;
  technologies: TechId[];
  lifecycle: Lifecycle;
  monthsSinceLastCommit: number;
  activityLevel: "High" | "Moderate" | "Low" | "Dormant";
  healthScore: number;
  documentationScore: number;
  testScore: number;
  intelligenceConfidence: number;
  ageYears: number;
  apis?: { name: string; protocol: string; endpointCount: number }[];
  hasIntent: boolean;
}

export const REPOSITORIES: SeedRepoDef[] = [
  // --- Payments domain ---
  {
    slug: "payment-gateway-service",
    name: "payment-gateway-service",
    description: "Core payment processing service handling card, ACH, and digital wallet transactions.",
    inferredPurpose: "Process customer payment transactions across multiple payment methods.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql", "tech-kafka"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 92, documentationScore: 85, testScore: 88, intelligenceConfidence: 95,
    ageYears: 5,
    apis: [{ name: "Payments API", protocol: "REST", endpointCount: 24 }],
    hasIntent: true,
  },
  {
    slug: "billing-invoicing-api",
    name: "billing-invoicing-api",
    description: "Generates and manages customer invoices and billing statements.",
    inferredPurpose: "Generate invoices and manage recurring billing cycles for customer accounts.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "High",
    healthScore: 88, documentationScore: 78, testScore: 82, intelligenceConfidence: 91,
    ageYears: 4,
    apis: [{ name: "Billing API", protocol: "REST", endpointCount: 18 }],
    hasIntent: true,
  },
  {
    slug: "settlement-reconciliation-worker",
    name: "settlement-reconciliation-worker",
    description: "Background worker reconciling settlement reports against internal ledgers.",
    inferredPurpose: "Reconcile daily settlement files from payment processors against internal transaction ledgers.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-python", "tech-postgresql", "tech-airflow"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 80, documentationScore: 65, testScore: 74, intelligenceConfidence: 87,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "legacy-payment-processor",
    name: "legacy-payment-processor",
    description: "Original payment processing system, largely superseded by payment-gateway-service.",
    inferredPurpose: "Legacy payment processing for a small number of remaining merchant integrations.",
    provider: "github", visibility: "private", team: "team-legacy-systems", domain: "domain-payments",
    technologies: ["tech-java", "tech-struts", "tech-oracle-db"],
    lifecycle: "Legacy", monthsSinceLastCommit: 14, activityLevel: "Low",
    healthScore: 41, documentationScore: 30, testScore: 25, intelligenceConfidence: 68,
    ageYears: 11,
    hasIntent: true,
  },
  {
    slug: "fraud-detection-engine",
    name: "fraud-detection-engine",
    description: "Real-time fraud scoring engine for inbound transactions.",
    inferredPurpose: "Score transactions in real time for fraud risk before authorization.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-python", "tech-kafka", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 90, documentationScore: 72, testScore: 85, intelligenceConfidence: 93,
    ageYears: 3,
    apis: [{ name: "Fraud Scoring API", protocol: "gRPC", endpointCount: 6 }],
    hasIntent: true,
  },
  {
    slug: "refund-processing-service",
    name: "refund-processing-service",
    description: "Handles refund requests and reversal workflows.",
    inferredPurpose: "Process customer refund requests and coordinate reversal with payment processors.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 5, activityLevel: "Low",
    healthScore: 71, documentationScore: 60, testScore: 68, intelligenceConfidence: 80,
    ageYears: 4,
    hasIntent: false,
  },

  // --- Identity domain ---
  {
    slug: "identity-auth-service",
    name: "identity-auth-service",
    description: "Central authentication service issuing and validating session tokens.",
    inferredPurpose: "Authenticate users and issue signed session tokens for internal and external applications.",
    provider: "github", visibility: "private", team: "team-identity", domain: "domain-identity",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 94, documentationScore: 88, testScore: 90, intelligenceConfidence: 96,
    ageYears: 4,
    apis: [{ name: "Auth API", protocol: "REST", endpointCount: 15 }],
    hasIntent: true,
  },
  {
    slug: "sso-gateway",
    name: "sso-gateway",
    description: "Single sign-on gateway federating identity across enterprise applications.",
    inferredPurpose: "Provide single sign-on federation across internal enterprise applications.",
    provider: "github", visibility: "private", team: "team-identity", domain: "domain-identity",
    technologies: ["tech-java", "tech-spring-boot"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 84, documentationScore: 75, testScore: 79, intelligenceConfidence: 89,
    ageYears: 3,
    apis: [{ name: "SSO API", protocol: "SAML/OIDC", endpointCount: 9 }],
    hasIntent: true,
  },
  {
    slug: "permissions-rbac-service",
    name: "permissions-rbac-service",
    description: "Role-based access control service for internal tooling.",
    inferredPurpose: "Manage roles, permissions, and access policies for internal applications.",
    provider: "gitlab", visibility: "private", team: "team-identity", domain: "domain-identity",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 79, documentationScore: 70, testScore: 72, intelligenceConfidence: 85,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "legacy-ldap-bridge",
    name: "legacy-ldap-bridge",
    description: "Bridges legacy LDAP directory to modern identity services.",
    inferredPurpose: "Synchronize legacy LDAP directory entries with the modern identity platform.",
    provider: "github", visibility: "private", team: "team-legacy-systems", domain: "domain-identity",
    technologies: ["tech-java", "tech-oracle-db"],
    lifecycle: "Dormant", monthsSinceLastCommit: 26, activityLevel: "Dormant",
    healthScore: 35, documentationScore: 20, testScore: 15, intelligenceConfidence: 55,
    ageYears: 9,
    hasIntent: false,
  },
  {
    slug: "api-key-management",
    name: "api-key-management",
    description: "Issues and rotates API keys for partner integrations.",
    inferredPurpose: "Issue, rotate, and revoke API keys for external partner integrations.",
    provider: "github", visibility: "private", team: "team-identity", domain: "domain-identity",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 4, activityLevel: "Low",
    healthScore: 74, documentationScore: 68, testScore: 70, intelligenceConfidence: 82,
    ageYears: 2,
    hasIntent: false,
  },

  // --- Customer Experience domain ---
  {
    slug: "customer-web-portal",
    name: "customer-web-portal",
    description: "Primary customer-facing web application for account management.",
    inferredPurpose: "Provide customers a self-service web portal for account and order management.",
    provider: "github", visibility: "internal", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-react", "tech-typescript", "tech-nodejs"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 91, documentationScore: 80, testScore: 83, intelligenceConfidence: 94,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "customer-mobile-app-backend",
    name: "customer-mobile-app-backend",
    description: "Backend-for-frontend API serving the customer mobile applications.",
    inferredPurpose: "Serve mobile-optimized APIs for the iOS and Android customer applications.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-nodejs", "tech-typescript", "tech-mongodb"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 89, documentationScore: 76, testScore: 80, intelligenceConfidence: 92,
    ageYears: 2,
    apis: [{ name: "Mobile BFF API", protocol: "REST", endpointCount: 32 }],
    hasIntent: true,
  },
  {
    slug: "notification-service",
    name: "notification-service",
    description: "Sends customer notifications via email and SMS channels.",
    inferredPurpose: "Provide customer notification services across email and SMS.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-nodejs", "tech-typescript", "tech-rabbitmq"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 82, documentationScore: 55, testScore: 70, intelligenceConfidence: 91,
    ageYears: 3,
    apis: [{ name: "Notification API", protocol: "REST", endpointCount: 11 }],
    hasIntent: true,
  },
  {
    slug: "customer-support-widget",
    name: "customer-support-widget",
    description: "Embeddable chat widget for customer support on the web portal.",
    inferredPurpose: "Provide an embeddable live-chat support widget for customer-facing sites.",
    provider: "github", visibility: "internal", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-react", "tech-typescript"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 6, activityLevel: "Low",
    healthScore: 68, documentationScore: 58, testScore: 55, intelligenceConfidence: 78,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "loyalty-rewards-service",
    name: "loyalty-rewards-service",
    description: "Manages customer loyalty points and rewards redemption.",
    inferredPurpose: "Track customer loyalty points and process rewards redemption.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 81, documentationScore: 66, testScore: 73, intelligenceConfidence: 86,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "customer-notification-preferences",
    name: "customer-notification-preferences",
    description: "Manages customer opt-in/opt-out preferences across notification channels.",
    inferredPurpose: "Store and enforce customer notification channel preferences.",
    provider: "gitlab", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 3, activityLevel: "Moderate",
    healthScore: 77, documentationScore: 62, testScore: 65, intelligenceConfidence: 84,
    ageYears: 1,
    hasIntent: true,
  },
  {
    slug: "legacy-customer-portal",
    name: "legacy-customer-portal",
    description: "Predecessor to customer-web-portal, retained for a subset of enterprise clients.",
    inferredPurpose: "Serve a legacy web experience to a shrinking set of enterprise clients not yet migrated.",
    provider: "github", visibility: "internal", team: "team-legacy-systems", domain: "domain-customer",
    technologies: ["tech-angularjs", "tech-jquery", "tech-mysql"],
    lifecycle: "Archive Candidate", monthsSinceLastCommit: 28, activityLevel: "Dormant",
    healthScore: 28, documentationScore: 15, testScore: 10, intelligenceConfidence: 62,
    ageYears: 8,
    hasIntent: true,
  },
  {
    slug: "email-alert-dispatcher-v1",
    name: "email-alert-dispatcher-v1",
    description: "Older email-only alert dispatch system, similar in scope to notification-service.",
    inferredPurpose: "Dispatch transactional email alerts to customers.",
    provider: "github", visibility: "private", team: "team-legacy-systems", domain: "domain-customer",
    technologies: ["tech-java", "tech-mysql"],
    lifecycle: "Archive Candidate", monthsSinceLastCommit: 25, activityLevel: "Dormant",
    healthScore: 32, documentationScore: 18, testScore: 20, intelligenceConfidence: 58,
    ageYears: 7,
    hasIntent: false,
  },

  // --- Fulfillment / Logistics domain ---
  {
    slug: "order-fulfillment-service",
    name: "order-fulfillment-service",
    description: "Orchestrates order fulfillment across warehouse and carrier systems.",
    inferredPurpose: "Orchestrate the fulfillment lifecycle of customer orders from confirmation to shipment.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-java", "tech-spring-boot", "tech-kafka", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 90, documentationScore: 79, testScore: 84, intelligenceConfidence: 93,
    ageYears: 4,
    apis: [{ name: "Fulfillment API", protocol: "REST", endpointCount: 21 }],
    hasIntent: true,
  },
  {
    slug: "warehouse-inventory-api",
    name: "warehouse-inventory-api",
    description: "Tracks real-time inventory levels across distribution centers.",
    inferredPurpose: "Track real-time inventory levels and reservations across distribution centers.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "High",
    healthScore: 87, documentationScore: 74, testScore: 78, intelligenceConfidence: 90,
    ageYears: 3,
    apis: [{ name: "Inventory API", protocol: "REST", endpointCount: 19 }],
    hasIntent: true,
  },
  {
    slug: "shipping-carrier-integration",
    name: "shipping-carrier-integration",
    description: "Integrates with third-party shipping carriers for rate quotes and label generation.",
    inferredPurpose: "Integrate with shipping carriers to fetch rates and generate shipping labels.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-python", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 80, documentationScore: 63, testScore: 71, intelligenceConfidence: 88,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "returns-processing-service",
    name: "returns-processing-service",
    description: "Manages customer return requests and warehouse intake.",
    inferredPurpose: "Manage the return merchandise authorization lifecycle from request to warehouse intake.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 5, activityLevel: "Low",
    healthScore: 70, documentationScore: 58, testScore: 62, intelligenceConfidence: 79,
    ageYears: 3,
    hasIntent: false,
  },
  {
    slug: "warehouse-robotics-controller",
    name: "warehouse-robotics-controller",
    description: "Experimental controller for automated warehouse picking robots.",
    inferredPurpose: "Control and coordinate automated picking robots in a pilot warehouse.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-python", "tech-kubernetes"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 66, documentationScore: 45, testScore: 50, intelligenceConfidence: 60,
    ageYears: 1,
    hasIntent: false,
  },
  {
    slug: "legacy-warehouse-management-system",
    name: "legacy-warehouse-management-system",
    description: "Original on-premise warehouse management system.",
    inferredPurpose: "Manage warehouse operations for facilities not yet migrated to the modern platform.",
    provider: "bitbucket", visibility: "internal", team: "team-legacy-systems", domain: "domain-fulfillment",
    technologies: ["tech-cobol", "tech-oracle-db"],
    lifecycle: "Legacy", monthsSinceLastCommit: 20, activityLevel: "Low",
    healthScore: 30, documentationScore: 22, testScore: 12, intelligenceConfidence: 65,
    ageYears: 16,
    hasIntent: true,
  },
  {
    slug: "delivery-route-optimizer",
    name: "delivery-route-optimizer",
    description: "Optimizes last-mile delivery routes for regional carriers.",
    inferredPurpose: "Compute optimized last-mile delivery routes for regional delivery fleets.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-python", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 78, documentationScore: 60, testScore: 68, intelligenceConfidence: 83,
    ageYears: 2,
    hasIntent: true,
  },

  // --- Analytics domain ---
  {
    slug: "analytics-ingestion-pipeline",
    name: "analytics-ingestion-pipeline",
    description: "Ingests event data from application services into the data warehouse.",
    inferredPurpose: "Ingest and normalize event data from application services into the enterprise data warehouse.",
    provider: "github", visibility: "private", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python", "tech-kafka", "tech-airflow"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 88, documentationScore: 73, testScore: 76, intelligenceConfidence: 90,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "reporting-dashboard-service",
    name: "reporting-dashboard-service",
    description: "Serves executive and operational reporting dashboards.",
    inferredPurpose: "Serve business reporting dashboards to executive and operational stakeholders.",
    provider: "github", visibility: "internal", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-react", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 84, documentationScore: 70, testScore: 72, intelligenceConfidence: 88,
    ageYears: 2,
    apis: [{ name: "Reporting API", protocol: "REST", endpointCount: 14 }],
    hasIntent: true,
  },
  {
    slug: "customer-data-warehouse-etl",
    name: "customer-data-warehouse-etl",
    description: "ETL jobs transforming raw customer data into warehouse-ready schemas.",
    inferredPurpose: "Transform raw customer event and transaction data into warehouse-ready analytical schemas.",
    provider: "github", visibility: "private", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python", "tech-airflow", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 81, documentationScore: 64, testScore: 70, intelligenceConfidence: 86,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "ml-recommendation-engine",
    name: "ml-recommendation-engine",
    description: "Generates personalized product recommendations from customer behavior data.",
    inferredPurpose: "Generate personalized product recommendations using customer behavioral and purchase data.",
    provider: "github", visibility: "private", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python", "tech-kubernetes"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 85, documentationScore: 60, testScore: 74, intelligenceConfidence: 89,
    ageYears: 2,
    apis: [{ name: "Recommendations API", protocol: "REST", endpointCount: 7 }],
    hasIntent: true,
  },
  {
    slug: "legacy-batch-reporting-job",
    name: "legacy-batch-reporting-job",
    description: "Nightly batch job producing legacy static reports, mostly superseded by reporting-dashboard-service.",
    inferredPurpose: "Produce nightly static operational reports for a small number of legacy report recipients.",
    provider: "bitbucket", visibility: "internal", team: "team-legacy-systems", domain: "domain-analytics",
    technologies: ["tech-java", "tech-oracle-db"],
    lifecycle: "Archive Candidate", monthsSinceLastCommit: 30, activityLevel: "Dormant",
    healthScore: 25, documentationScore: 12, testScore: 8, intelligenceConfidence: 60,
    ageYears: 10,
    hasIntent: false,
  },
  {
    slug: "experimental-forecasting-model",
    name: "experimental-forecasting-model",
    description: "Prototype demand forecasting model, not yet in production use.",
    inferredPurpose: "Prototype demand forecasting for inventory planning; not yet production-integrated.",
    provider: "github", visibility: "private", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python"],
    lifecycle: "Dormant", monthsSinceLastCommit: 9, activityLevel: "Dormant",
    healthScore: 48, documentationScore: 35, testScore: 20, intelligenceConfidence: 50,
    ageYears: 1,
    hasIntent: false,
  },

  // --- Marketing domain ---
  {
    slug: "campaign-management-service",
    name: "campaign-management-service",
    description: "Manages marketing campaign definitions and scheduling.",
    inferredPurpose: "Define, schedule, and track marketing campaigns across channels.",
    provider: "github", visibility: "private", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 82, documentationScore: 68, testScore: 71, intelligenceConfidence: 87,
    ageYears: 2,
    apis: [{ name: "Campaigns API", protocol: "REST", endpointCount: 16 }],
    hasIntent: true,
  },
  {
    slug: "crm-integration-service",
    name: "crm-integration-service",
    description: "Synchronizes customer records between internal systems and the CRM platform.",
    inferredPurpose: "Synchronize customer and lead records between internal systems and the CRM platform.",
    provider: "github", visibility: "private", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-nodejs", "tech-typescript"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 76, documentationScore: 58, testScore: 62, intelligenceConfidence: 83,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "email-marketing-templates",
    name: "email-marketing-templates",
    description: "Shared repository of responsive email marketing templates.",
    inferredPurpose: "House shared, responsive email templates used across marketing campaigns.",
    provider: "github", visibility: "internal", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-react"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 4, activityLevel: "Low",
    healthScore: 65, documentationScore: 50, testScore: 30, intelligenceConfidence: 70,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "personalization-engine",
    name: "personalization-engine",
    description: "Real-time content personalization for marketing surfaces.",
    inferredPurpose: "Personalize on-site and email content in real time based on customer segments.",
    provider: "github", visibility: "private", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-python", "tech-kafka"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 79, documentationScore: 55, testScore: 65, intelligenceConfidence: 81,
    ageYears: 1,
    hasIntent: true,
  },
  {
    slug: "legacy-marketing-automation-tool",
    name: "legacy-marketing-automation-tool",
    description: "Older marketing automation tool, largely replaced by campaign-management-service.",
    inferredPurpose: "Automate legacy drip email campaigns for a small remaining set of workflows.",
    provider: "github", visibility: "internal", team: "team-legacy-systems", domain: "domain-marketing",
    technologies: ["tech-java", "tech-mysql"],
    lifecycle: "Archive Candidate", monthsSinceLastCommit: 22, activityLevel: "Dormant",
    healthScore: 33, documentationScore: 20, testScore: 15, intelligenceConfidence: 64,
    ageYears: 6,
    hasIntent: false,
  },

  // --- Platform / Internal domain ---
  {
    slug: "ci-cd-pipeline-templates",
    name: "ci-cd-pipeline-templates",
    description: "Shared CI/CD pipeline configuration templates used across engineering teams.",
    inferredPurpose: "Provide reusable CI/CD pipeline templates and standards for engineering teams.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-terraform"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 90, documentationScore: 85, testScore: 60, intelligenceConfidence: 92,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "infra-terraform-modules",
    name: "infra-terraform-modules",
    description: "Reusable Terraform modules for provisioning cloud infrastructure.",
    inferredPurpose: "Provide reusable, versioned Terraform modules for provisioning cloud infrastructure.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-terraform", "tech-kubernetes"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 93, documentationScore: 87, testScore: 55, intelligenceConfidence: 94,
    ageYears: 3,
    hasIntent: true,
  },
  {
    slug: "shared-ui-component-library",
    name: "shared-ui-component-library",
    description: "Shared React component library implementing the enterprise design system.",
    inferredPurpose: "Provide a shared, versioned React component library implementing the enterprise design system.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-react", "tech-typescript"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 89, documentationScore: 82, testScore: 78, intelligenceConfidence: 93,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "api-gateway",
    name: "api-gateway",
    description: "Central API gateway routing and rate-limiting traffic to internal services.",
    inferredPurpose: "Route, authenticate, and rate-limit traffic to internal microservices.",
    provider: "github", visibility: "private", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript", "tech-kubernetes"],
    lifecycle: "Active", monthsSinceLastCommit: 0, activityLevel: "High",
    healthScore: 92, documentationScore: 80, testScore: 85, intelligenceConfidence: 95,
    ageYears: 4,
    apis: [{ name: "Gateway Admin API", protocol: "REST", endpointCount: 10 }],
    hasIntent: true,
  },
  {
    slug: "observability-metrics-service",
    name: "observability-metrics-service",
    description: "Aggregates application metrics and exposes dashboards for on-call teams.",
    inferredPurpose: "Aggregate application and infrastructure metrics for observability dashboards and alerting.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 85, documentationScore: 70, testScore: 72, intelligenceConfidence: 88,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "feature-flag-service",
    name: "feature-flag-service",
    description: "Manages feature flags and gradual rollout configuration across applications.",
    inferredPurpose: "Manage feature flags and gradual rollout configuration for internal applications.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 83, documentationScore: 72, testScore: 74, intelligenceConfidence: 87,
    ageYears: 2,
    apis: [{ name: "Feature Flags API", protocol: "REST", endpointCount: 8 }],
    hasIntent: true,
  },
  {
    slug: "internal-developer-cli",
    name: "internal-developer-cli",
    description: "Command-line tool for scaffolding and managing internal services.",
    inferredPurpose: "Provide a CLI for scaffolding, testing, and deploying internal services.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 3, activityLevel: "Low",
    healthScore: 75, documentationScore: 68, testScore: 60, intelligenceConfidence: 80,
    ageYears: 3,
    hasIntent: false,
  },
  {
    slug: "secrets-management-service",
    name: "secrets-management-service",
    description: "Manages application secrets and integrates with the enterprise vault.",
    inferredPurpose: "Manage and rotate application secrets, integrating with the enterprise vault.",
    provider: "github", visibility: "private", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-java", "tech-kubernetes"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 88, documentationScore: 74, testScore: 80, intelligenceConfidence: 91,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "config-management-service",
    name: "config-management-service",
    description: "Centralized application configuration and environment variable management.",
    inferredPurpose: "Provide centralized, versioned application configuration across environments.",
    provider: "gitlab", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 80, documentationScore: 66, testScore: 69, intelligenceConfidence: 85,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "internal-status-page",
    name: "internal-status-page",
    description: "Internal service status and incident communication page.",
    inferredPurpose: "Communicate service status and incident updates to internal stakeholders.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-react", "tech-typescript"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 5, activityLevel: "Low",
    healthScore: 69, documentationScore: 55, testScore: 50, intelligenceConfidence: 76,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "legacy-jenkins-pipeline-scripts",
    name: "legacy-jenkins-pipeline-scripts",
    description: "Old Jenkins pipeline scripts, largely replaced by ci-cd-pipeline-templates.",
    inferredPurpose: "Run legacy Jenkins-based build pipelines for a shrinking set of older services.",
    provider: "bitbucket", visibility: "internal", team: "team-legacy-systems", domain: "domain-platform",
    technologies: ["tech-java"],
    lifecycle: "Archive Candidate", monthsSinceLastCommit: 24, activityLevel: "Dormant",
    healthScore: 29, documentationScore: 18, testScore: 10, intelligenceConfidence: 61,
    ageYears: 9,
    hasIntent: false,
  },
  {
    slug: "monorepo-build-tooling",
    name: "monorepo-build-tooling",
    description: "Shared build tooling and scripts for the frontend monorepo.",
    inferredPurpose: "Provide shared build, lint, and release tooling for frontend monorepo packages.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-typescript", "tech-nodejs"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 84, documentationScore: 71, testScore: 68, intelligenceConfidence: 86,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "data-anonymization-utility",
    name: "data-anonymization-utility",
    description: "Utility library for anonymizing PII in non-production data sets.",
    inferredPurpose: "Anonymize personally identifiable information in data exported to non-production environments.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-python"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 7, activityLevel: "Low",
    healthScore: 72, documentationScore: 60, testScore: 65, intelligenceConfidence: 78,
    ageYears: 3,
    hasIntent: false,
  },
  {
    slug: "batch-job-scheduler",
    name: "batch-job-scheduler",
    description: "Schedules and monitors internal batch and cron jobs.",
    inferredPurpose: "Schedule, monitor, and alert on internal batch and cron job execution.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-python", "tech-airflow"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 81, documentationScore: 63, testScore: 70, intelligenceConfidence: 85,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "internal-search-service",
    name: "internal-search-service",
    description: "Search indexing and query service used by internal tools.",
    inferredPurpose: "Index and serve search queries for internal knowledge and tooling systems.",
    provider: "github", visibility: "internal", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-java", "tech-spring-boot"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 6, activityLevel: "Low",
    healthScore: 70, documentationScore: 52, testScore: 58, intelligenceConfidence: 75,
    ageYears: 3,
    hasIntent: false,
  },
  {
    slug: "webhook-relay-service",
    name: "webhook-relay-service",
    description: "Relays and retries inbound/outbound webhooks between internal and partner systems.",
    inferredPurpose: "Relay and reliably retry webhook delivery between internal services and partner systems.",
    provider: "github", visibility: "private", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript", "tech-rabbitmq"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 83, documentationScore: 67, testScore: 71, intelligenceConfidence: 87,
    ageYears: 1,
    hasIntent: true,
  },
  {
    slug: "experimental-graphql-gateway",
    name: "experimental-graphql-gateway",
    description: "Prototype GraphQL federation layer over existing REST services.",
    inferredPurpose: "Prototype a GraphQL federation layer over existing internal REST services.",
    provider: "github", visibility: "private", team: "team-platform", domain: "domain-platform",
    technologies: ["tech-nodejs", "tech-typescript"],
    lifecycle: "Dormant", monthsSinceLastCommit: 10, activityLevel: "Dormant",
    healthScore: 45, documentationScore: 40, testScore: 25, intelligenceConfidence: 48,
    ageYears: 1,
    hasIntent: false,
  },
  {
    slug: "mainframe-integration-adapter",
    name: "mainframe-integration-adapter",
    description: "Adapter translating mainframe batch outputs into modern service events.",
    inferredPurpose: "Translate legacy mainframe batch file outputs into modern event streams.",
    provider: "bitbucket", visibility: "private", team: "team-legacy-systems", domain: "domain-platform",
    technologies: ["tech-cobol", "tech-java"],
    lifecycle: "Legacy", monthsSinceLastCommit: 16, activityLevel: "Low",
    healthScore: 38, documentationScore: 25, testScore: 18, intelligenceConfidence: 66,
    ageYears: 14,
    hasIntent: true,
  },
  {
    slug: "unused-prototype-dashboard",
    name: "unused-prototype-dashboard",
    description: "Abandoned prototype dashboard with no clear current owner.",
    inferredPurpose: "Unclear — appears to be an abandoned internal prototype dashboard.",
    provider: "github", visibility: "internal", team: null, domain: "domain-platform",
    technologies: ["tech-react"],
    lifecycle: "Unknown", monthsSinceLastCommit: 19, activityLevel: "Dormant",
    healthScore: 22, documentationScore: 10, testScore: 5, intelligenceConfidence: 30,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "orphaned-integration-scripts",
    name: "orphaned-integration-scripts",
    description: "Collection of one-off integration scripts without a clear owning team.",
    inferredPurpose: "Unclear — a collection of ad hoc integration scripts accumulated over time.",
    provider: "github", visibility: "internal", team: null, domain: null,
    technologies: ["tech-python"],
    lifecycle: "Unknown", monthsSinceLastCommit: 21, activityLevel: "Dormant",
    healthScore: 20, documentationScore: 8, testScore: 5, intelligenceConfidence: 25,
    ageYears: 4,
    hasIntent: false,
  },
  {
    slug: "regional-tax-calculation-service",
    name: "regional-tax-calculation-service",
    description: "Calculates applicable sales tax by jurisdiction for order totals.",
    inferredPurpose: "Calculate applicable sales tax for order totals based on shipping jurisdiction.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 84, documentationScore: 69, testScore: 76, intelligenceConfidence: 88,
    ageYears: 3,
    apis: [{ name: "Tax Calculation API", protocol: "REST", endpointCount: 6 }],
    hasIntent: true,
  },
  {
    slug: "subscription-management-service",
    name: "subscription-management-service",
    description: "Manages recurring subscription plans and lifecycle state.",
    inferredPurpose: "Manage recurring subscription plans, upgrades, downgrades, and cancellations.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "High",
    healthScore: 87, documentationScore: 73, testScore: 79, intelligenceConfidence: 90,
    ageYears: 2,
    apis: [{ name: "Subscriptions API", protocol: "REST", endpointCount: 20 }],
    hasIntent: true,
  },
  {
    slug: "vendor-payout-service",
    name: "vendor-payout-service",
    description: "Calculates and issues payouts to third-party marketplace vendors.",
    inferredPurpose: "Calculate and issue periodic payouts to third-party marketplace vendors.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 82, documentationScore: 65, testScore: 73, intelligenceConfidence: 86,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "mobile-push-notification-gateway",
    name: "mobile-push-notification-gateway",
    description: "Sends push notifications to iOS and Android customer apps.",
    inferredPurpose: "Deliver push notifications to iOS and Android customer applications.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-nodejs", "tech-typescript"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 80, documentationScore: 61, testScore: 68, intelligenceConfidence: 85,
    ageYears: 2,
    apis: [{ name: "Push Notification API", protocol: "REST", endpointCount: 5 }],
    hasIntent: true,
  },
  {
    slug: "wishlist-favorites-service",
    name: "wishlist-favorites-service",
    description: "Stores customer wishlist and favorited product data.",
    inferredPurpose: "Store and retrieve customer wishlist and favorited product data.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-nodejs", "tech-typescript", "tech-mongodb"],
    lifecycle: "Active", monthsSinceLastCommit: 3, activityLevel: "Low",
    healthScore: 75, documentationScore: 58, testScore: 62, intelligenceConfidence: 80,
    ageYears: 1,
    hasIntent: false,
  },
  {
    slug: "review-ratings-service",
    name: "review-ratings-service",
    description: "Manages customer product reviews and ratings.",
    inferredPurpose: "Store, moderate, and serve customer product reviews and ratings.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 79, documentationScore: 62, testScore: 67, intelligenceConfidence: 84,
    ageYears: 2,
    apis: [{ name: "Reviews API", protocol: "REST", endpointCount: 9 }],
    hasIntent: true,
  },
  {
    slug: "search-catalog-indexer",
    name: "search-catalog-indexer",
    description: "Indexes product catalog data for on-site search.",
    inferredPurpose: "Index product catalog data to power on-site product search.",
    provider: "github", visibility: "private", team: "team-customer-exp", domain: "domain-customer",
    technologies: ["tech-java", "tech-kafka"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 83, documentationScore: 66, testScore: 71, intelligenceConfidence: 87,
    ageYears: 2,
    hasIntent: true,
  },
  {
    slug: "gift-card-service",
    name: "gift-card-service",
    description: "Issues and redeems digital gift cards.",
    inferredPurpose: "Issue, track balances for, and redeem digital gift cards.",
    provider: "github", visibility: "private", team: "team-payments", domain: "domain-payments",
    technologies: ["tech-java", "tech-spring-boot", "tech-postgresql"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 4, activityLevel: "Low",
    healthScore: 73, documentationScore: 59, testScore: 64, intelligenceConfidence: 79,
    ageYears: 3,
    hasIntent: false,
  },
  {
    slug: "supplier-edi-integration",
    name: "supplier-edi-integration",
    description: "Processes EDI documents exchanged with wholesale suppliers.",
    inferredPurpose: "Process EDI purchase orders and invoices exchanged with wholesale suppliers.",
    provider: "azure-devops", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-dotnet", "tech-mysql"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 6, activityLevel: "Low",
    healthScore: 68, documentationScore: 50, testScore: 55, intelligenceConfidence: 74,
    ageYears: 5,
    hasIntent: true,
  },
  {
    slug: "returns-fraud-heuristics",
    name: "returns-fraud-heuristics",
    description: "Experimental heuristics for flagging suspicious return patterns.",
    inferredPurpose: "Flag potentially fraudulent return patterns using rule-based heuristics.",
    provider: "github", visibility: "private", team: "team-logistics", domain: "domain-fulfillment",
    technologies: ["tech-python"],
    lifecycle: "Dormant", monthsSinceLastCommit: 11, activityLevel: "Dormant",
    healthScore: 44, documentationScore: 30, testScore: 22, intelligenceConfidence: 45,
    ageYears: 1,
    hasIntent: false,
  },
  {
    slug: "data-quality-monitor",
    name: "data-quality-monitor",
    description: "Monitors data pipelines for schema drift and quality regressions.",
    inferredPurpose: "Monitor enterprise data pipelines for schema drift and quality regressions.",
    provider: "github", visibility: "internal", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python", "tech-airflow"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 78, documentationScore: 61, testScore: 67, intelligenceConfidence: 82,
    ageYears: 1,
    hasIntent: false,
  },
  {
    slug: "customer-churn-prediction",
    name: "customer-churn-prediction",
    description: "Predictive model estimating customer churn risk.",
    inferredPurpose: "Predict customer churn risk to inform retention campaigns.",
    provider: "github", visibility: "private", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python"],
    lifecycle: "Active", monthsSinceLastCommit: 2, activityLevel: "Moderate",
    healthScore: 77, documentationScore: 55, testScore: 60, intelligenceConfidence: 80,
    ageYears: 1,
    hasIntent: true,
  },
  {
    slug: "ab-testing-platform",
    name: "ab-testing-platform",
    description: "Manages experiment configuration and statistical analysis for A/B tests.",
    inferredPurpose: "Configure experiments and compute statistical significance for A/B tests across products.",
    provider: "github", visibility: "internal", team: "team-data", domain: "domain-analytics",
    technologies: ["tech-python", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 1, activityLevel: "Moderate",
    healthScore: 82, documentationScore: 68, testScore: 72, intelligenceConfidence: 86,
    ageYears: 2,
    apis: [{ name: "Experiments API", protocol: "REST", endpointCount: 12 }],
    hasIntent: true,
  },
  {
    slug: "social-media-listening-tool",
    name: "social-media-listening-tool",
    description: "Aggregates and analyzes social media mentions of company brands.",
    inferredPurpose: "Aggregate and sentiment-score social media mentions of company brands.",
    provider: "github", visibility: "private", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-python"],
    lifecycle: "Maintenance", monthsSinceLastCommit: 5, activityLevel: "Low",
    healthScore: 66, documentationScore: 48, testScore: 40, intelligenceConfidence: 70,
    ageYears: 2,
    hasIntent: false,
  },
  {
    slug: "affiliate-tracking-service",
    name: "affiliate-tracking-service",
    description: "Tracks affiliate referral links and commission attribution.",
    inferredPurpose: "Track affiliate referral clicks and attribute commissions to conversions.",
    provider: "github", visibility: "private", team: "team-marketing-tech", domain: "domain-marketing",
    technologies: ["tech-nodejs", "tech-typescript", "tech-postgresql"],
    lifecycle: "Active", monthsSinceLastCommit: 3, activityLevel: "Low",
    healthScore: 74, documentationScore: 57, testScore: 61, intelligenceConfidence: 78,
    ageYears: 2,
    hasIntent: false,
  },
];
